development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async

# production:
#   adapter: redis
#   host: ec2-34-232-179-152.compute-1.amazonaws.com
#   port: 55749
#   password: pcb3f74490a16460bd4811fbf404ac26f798cb70aecd35f37e4955f2fa76a233e
#   inline: true
#   timeout: 1
#   #url: ENV.fetch('REDIS_URL')
