development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async

# production:
#   adapter: redis
#   host: ec2-1-2-3-4.compute-1.amazonaws.com
#   port: 55749
#   password: password
#   inline: true
#   timeout: 1
